---
#
# Playbook to install the ELK stack
#

- hosts: elk
  user: thomas.jackson
  become_method: sudo
  become_user: root
  roles:
    - { role: elasticsearch }
    - { role: fluentd, when: (logging_backend == 'fluentd') }
    - { role: logstash, when: ((logging_backend is none) or (logging_backend == 'logstash')) }
    - { role: nginx }
    - { role: curator, when: install_curator_tool }
    - { role: kibana }
